name: F1Tracker cron job
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  schedule:
    - cron: 21 21 * * *

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run your script
        run: |
          python F1Tracker.py
